# Generated by Django 6.0 on 2026-01-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('icon_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('category', models.CharField(choices=[('Conference', 'Conference'), ('Partnership', 'Partnership'), ('Admissions', 'Admissions'), ('Announcement', 'Announcement'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('country_en', models.CharField(max_length=100)),
                ('country_fr', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('International', 'International'), ('National', 'National')], max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('icon_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('file', models.FileField(upload_to='tenders/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('news_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.newsevent')),
            ],
        ),
    ]
